name: "Hello Actions"

on:
    workflow_dispatch:

jobs:
    - name: "Greeting"
      inputs:
            MY_NAME:
            description: "Who to greet"
            required: true
            default: "World"

      runs:
            usses: "docker"
            image: "Dockerfile"
    
      branding:
            icon: "mic"
            color: "purple"
